import { describe, expect, it } from "vitest";
import {
  createMachinaStyleArtifact,
  formatMachinaStyleDiagnostics,
  S,
  serializeMachinaStyleSheet,
  validateMachinaStyleSheet,
  type MachinaStyleRecord,
  type MachinaStyleSheet,
} from "../src/style";

describe("MachinaStyle authoring", () => {
  it("exports the S namespace and style utilities", () => {
    expect(S.style).toBeTypeOf("function");
    expect(S.with).toBeTypeOf("function");
    expect(S.sheet).toBeTypeOf("function");
    expect(S.token).toBeTypeOf("function");
    expect(S.classes).toBeTypeOf("function");
    expect(createMachinaStyleArtifact).toBeTypeOf("function");
    expect(serializeMachinaStyleSheet).toBeTypeOf("function");
    expect(validateMachinaStyleSheet).toBeTypeOf("function");
  });

  it("returns fresh token and style records without mutating input", () => {
    const inputTokens = {
      color: { primary: "#7c5cff" },
      space: { md: 16 },
    };
    const inputStyle: MachinaStyleRecord = {
      surface: { fill: "color.primary" },
      box: { paddingX: "space.md" },
    };

    const tokens = S.tokens(inputTokens);
    const style = S.style(inputStyle);

    expect(tokens).toEqual(inputTokens);
    expect(tokens).not.toBe(inputTokens);
    expect(tokens.color).not.toBe(inputTokens.color);
    expect(style).toEqual(inputStyle);
    expect(style).not.toBe(inputStyle);
    expect(style.surface).not.toBe(inputStyle.surface);
  });

  it("deep-merges records immutably and ignores undefined patch values", () => {
    const base = S.style({
      box: { paddingX: 8, paddingY: 4 },
      surface: { fill: "color.panel", radius: 12 },
      text: { weight: "normal" },
    });
    const patch: MachinaStyleRecord = {
      box: { paddingX: undefined, gap: 10 },
      surface: { fill: "color.primary" },
      text: { weight: "semibold" },
    };

    const merged = S.with(base, patch);

    expect(merged).toEqual({
      box: { paddingX: 8, paddingY: 4, gap: 10 },
      surface: { fill: "color.primary", radius: 12 },
      text: { weight: "semibold" },
      border: undefined,
      effect: undefined,
    });
    expect(base).toEqual({
      box: { paddingX: 8, paddingY: 4 },
      surface: { fill: "color.panel", radius: 12 },
      text: { weight: "normal" },
    });
    expect(patch).toEqual({
      box: { paddingX: undefined, gap: 10 },
      surface: { fill: "color.primary" },
      text: { weight: "semibold" },
    });
  });

  it("creates fresh sheets with tokens and classes", () => {
    const input: MachinaStyleSheet = {
      tokens: { radius: { md: 12 } },
      classes: {
        panel: { surface: { radius: "radius.md" } },
      },
    };

    const sheet = S.sheet(input);

    expect(sheet).toEqual(input);
    expect(sheet).not.toBe(input);
    expect(sheet.tokens).not.toBe(input.tokens);
    expect(sheet.classes).not.toBe(input.classes);
    expect(sheet.classes.panel).not.toBe(input.classes.panel);
  });

  it("rejects empty class names during authoring", () => {
    expect(() => S.sheet({ classes: { "": {} } })).toThrow(/non-empty/);
  });
});

describe("MachinaStyle serialization", () => {
  const sheet = S.sheet({
    tokens: S.tokens({
      color: {
        onPrimary: "#ffffff",
        page: "#0b0d12",
        primary: "#7c5cff",
      },
      space: {
        md: 16,
        sm: 8,
      },
      radius: {
        lg: 20,
        md: 12,
      },
      font: {
        ui: {
          family: "Inter, system-ui, sans-serif",
          size: 14,
          lineHeight: 1.45,
          weight: "medium",
        },
      },
      shadow: {
        card: "0 16px 40px rgba(0, 0, 0, 0.25)",
      },
    }),
    classes: {
      primaryButton: S.style({
        box: {
          display: "inlineBlock",
          paddingX: "space.md",
          paddingY: "space.sm",
          alignItems: "start",
          justifyContent: "spaceBetween",
        },
        surface: {
          fill: S.token("color", "primary"),
          radius: "radius.md",
        },
        text: {
          color: "color.onPrimary",
          font: S.token("font", "ui"),
          size: 16,
          weight: "semibold",
        },
        effect: {
          shadow: "shadow.card",
        },
      }),
    },
  });

  it("lowers tokens, semantic records, enums, weights, and token refs to deterministic CSS", () => {
    expect(
      serializeMachinaStyleSheet(sheet),
    ).toBe(`/* Generated by MachinaStyle. Edit style.ts, not this CSS. */

/* biome-ignore-all lint/suspicious/noDuplicateProperties: Font token expansion intentionally emits base declarations before explicit overrides. */

:root {
  --color-on-primary: #ffffff;
  --color-page: #0b0d12;
  --color-primary: #7c5cff;
  --space-md: 16px;
  --space-sm: 8px;
  --radius-lg: 20px;
  --radius-md: 12px;
  --font-ui-family: Inter, system-ui, sans-serif;
  --font-ui-size: 14px;
  --font-ui-line-height: 1.45;
  --font-ui-weight: 500;
  --shadow-card: 0 16px 40px rgba(0, 0, 0, 0.25);
}

.primaryButton {
  display: inline-block;
  padding-left: var(--space-md);
  padding-right: var(--space-md);
  padding-top: var(--space-sm);
  padding-bottom: var(--space-sm);
  align-items: flex-start;
  justify-content: space-between;
  background: var(--color-primary);
  border-radius: var(--radius-md);
  color: var(--color-on-primary);
  font-family: var(--font-ui-family);
  font-size: var(--font-ui-size);
  line-height: var(--font-ui-line-height);
  font-weight: var(--font-ui-weight);
  font-size: 16px;
  font-weight: 600;
  box-shadow: var(--shadow-card);
}
`);
  });

  it("can omit the generated header", () => {
    expect(serializeMachinaStyleSheet(sheet, { includeHeader: false }).startsWith(":root")).toBe(
      true,
    );
  });

  it("is stable regardless of input class insertion order", () => {
    const first = S.sheet({
      classes: {
        zebra: { surface: { fill: "black" } },
        alpha: { surface: { fill: "white" } },
      },
    });
    const second = S.sheet({
      classes: {
        alpha: { surface: { fill: "white" } },
        zebra: { surface: { fill: "black" } },
      },
    });

    expect(serializeMachinaStyleSheet(first)).toBe(serializeMachinaStyleSheet(second));
  });
});

describe("MachinaStyle validation", () => {
  it("accepts a valid sheet", () => {
    const sheet = S.sheet({
      tokens: {
        color: { primary: "#7c5cff" },
        radius: { md: 12 },
        font: {
          ui: {
            family: "Inter, system-ui, sans-serif",
          },
        },
      },
      classes: {
        card: {
          surface: { fill: "color.primary", radius: "radius.md", opacity: 0.8 },
          text: { font: "font.ui" },
          border: { width: 1 },
        },
      },
    });

    expect(validateMachinaStyleSheet(sheet)).toEqual([]);
  });

  it("reports invalid opacity, negative radius, negative border width, and unknown token refs", () => {
    const diagnostics = validateMachinaStyleSheet({
      tokens: {
        radius: { bad: -1 },
      },
      classes: {
        badCard: {
          surface: { fill: S.token("color", "missing"), radius: -2, opacity: 1.2 },
          border: { width: -1 },
        },
      },
    });

    expect(diagnostics.map((diagnostic) => diagnostic.code)).toEqual([
      "NegativeRadiusToken",
      "InvalidOpacity",
      "NegativeRadius",
      "NegativeBorderWidth",
      "UnknownTokenReference",
    ]);
  });

  it("formats diagnostics with codes and messages", () => {
    const diagnostics = validateMachinaStyleSheet({
      classes: {
        "bad card": {
          surface: { opacity: 2 },
        },
      },
    });

    const formatted = formatMachinaStyleDiagnostics(diagnostics);

    expect(formatted).toContain("InvalidClassName");
    expect(formatted).toContain("InvalidOpacity");
    expect(formatted).toContain("MachinaStyle surface opacity must be between 0 and 1.");
  });
});
