/* @vitest-environment jsdom */
import "@testing-library/jest-dom/vitest";
import { describe, expect, it } from "vitest";
import { defineComponent, h } from "vue";
import { mount } from "@vue/test-utils";
import type { Rect, ResolvedLayoutDocument } from "../../src";
import { MachinaVueView } from "../../src/vue";

const makeLayout=(rootRect:Rect,childRect:Rect):ResolvedLayoutDocument=>({rootId:"root",nodes:{root:{id:"root",rect:rootRect,frame:{kind:"absolute",...rootRect}},child:{id:"child",rect:childRect,frame:{kind:"absolute",...childRect},slot:"Sidebar",debugLabel:"child-label"}},children:{root:["child"],child:[]}});

describe("MachinaVueView",()=>{
  it("renders without crashing",()=>{const w=mount(MachinaVueView,{props:{layout:makeLayout({x:0,y:0,width:800,height:600},{x:16,y:12,width:100,height:50})}}); expect(w.find('[data-machina-root-id="root"]').exists()).toBe(true); expect(w.find('[data-machina-node-id="child"]').exists()).toBe(true);});
  it("applies absolute styles and nested normalization",()=>{const layout:ResolvedLayoutDocument={rootId:"root",nodes:{root:{id:"root",rect:{x:0,y:0,width:1100,height:720},frame:{kind:"absolute",x:0,y:0,width:1100,height:720}},main:{id:"main",rect:{x:268,y:88,width:816,height:616},frame:{kind:"absolute",x:268,y:88,width:816,height:616}},toolbar:{id:"toolbar",rect:{x:284,y:104,width:784,height:48},frame:{kind:"absolute",x:284,y:104,width:784,height:48}}},children:{root:["main"],main:["toolbar"],toolbar:[]}}; const w=mount(MachinaVueView,{props:{layout}}); expect(w.find('[data-machina-node-id="main"]').attributes("style")).toContain("left: 268px"); expect(w.find('[data-machina-node-id="toolbar"]').attributes("style")).toContain("left: 16px");});
  it("view/slot precedence and data forwarding",()=>{const Probe=defineComponent({props:{id:{type:String,required:true},viewKey:{type:String,required:false},viewData:{type:Object,required:false},nodeData:{type:Object,required:false}},setup:(p:any)=>()=>h("div",`${p.id}-${p.viewKey}-${p.viewData?.m}-${p.nodeData?.n}`)}); const layout=makeLayout({x:0,y:0,width:100,height:100},{x:1,y:2,width:3,height:4}); layout.nodes.child.view="Panel"; layout.nodes.child.slot="Fallback"; const w=mount(MachinaVueView,{props:{layout,views:{Panel:Probe,Fallback:()=>h("div","no")},viewData:{Panel:{m:"v"}},nodeData:{child:{n:"d"}}}}); expect(w.text()).toContain("child-Panel-v-d"); expect(w.text()).not.toContain("no");});
  it("sorts by layer/z and fallbacks invalid layer z",()=>{const layout:ResolvedLayoutDocument={rootId:"root",nodes:{root:{id:"root",rect:{x:0,y:0,width:10,height:10},frame:{kind:"absolute",x:0,y:0,width:10,height:10}},a:{id:"a",layer:"overlay",z:0,rect:{x:0,y:0,width:1,height:1},frame:{kind:"absolute",x:0,y:0,width:1,height:1}},b:{id:"b",layer:"bad",z:0,rect:{x:0,y:0,width:1,height:1},frame:{kind:"absolute",x:0,y:0,width:1,height:1}},c:{id:"c",layer:"overlay",z:-1,rect:{x:0,y:0,width:1,height:1},frame:{kind:"absolute",x:0,y:0,width:1,height:1}}},children:{root:["a","b","c"],a:[],b:[],c:[]}}; const w=mount(MachinaVueView,{props:{layout,layers:{overlay:{z:4},bad:{z:99 as any}}}}); const ids=w.find('[data-machina-node-id="root"]').element.children; expect(Array.from(ids).map((n)=>n.getAttribute("data-machina-node-id"))).toEqual(["b","c","a"]);});
  it("supports containment/debug/style props and does not mutate input",()=>{const layout=makeLayout({x:100,y:200,width:800,height:600},{x:150,y:250,width:50,height:40}); const snap=JSON.stringify(layout); const w=mount(MachinaVueView,{props:{layout,debug:true,rootClass:"root-c",rootStyle:{overflow:"hidden"},nodeClass:"node-c",nodeContainment:"strict",nodeContentVisibility:"auto",nodeContainIntrinsicSize:"auto 300px",nodeStyle:{opacity:"0.8"}} as any}); expect(w.find('[data-machina-root-id="root"]').classes()).toContain("root-c"); const child=w.find('[data-machina-node-id="child"]'); expect(child.attributes("style")).toContain("contain: strict"); expect(child.attributes("style")).toContain("content-visibility: auto"); expect(w.text()).toContain("child-label"); expect(JSON.stringify(layout)).toBe(snap);});
});
