import {
  Boundaries,
  Package,
  Policies,
  Publish,
  Targets,
  Tools,
  Workspace,
  define,
  defineDeps,
  npm,
  peer,
  tool,
} from "tspack/manifest";

// This is a shadow contract for M44a. package.json and package-lock.json remain
// the publish and installation source of truth.
const deps = defineDeps({
  biome: tool(npm("@biomejs/biome", "^2.4.15"), { key: "@biomejs/biome" }),
  testingLibraryJestDom: tool(npm("@testing-library/jest-dom", "^6.9.1"), {
    key: "@testing-library/jest-dom",
  }),
  testingLibraryReact: tool(npm("@testing-library/react", "^16.3.2"), {
    key: "@testing-library/react",
  }),
  typesReact: tool(npm("@types/react", "^19.2.14"), { key: "@types/react" }),
  typesReactDom: tool(npm("@types/react-dom", "^19.2.3"), { key: "@types/react-dom" }),
  typesReactTestRenderer: tool(npm("@types/react-test-renderer", "^19.1.0"), {
    key: "@types/react-test-renderer",
  }),
  vueTestUtils: tool(npm("@vue/test-utils", "^2.4.6"), { key: "@vue/test-utils" }),
  jsdom: tool(npm("jsdom", "^29.1.1")),
  reactTestRenderer: tool(npm("react-test-renderer", "^19.2.6"), { key: "react-test-renderer" }),
  tsup: tool(npm("tsup", "^8.5.1")),
  typescript: tool(npm("typescript", "^5.6.3")),
  vitest: tool(npm("vitest", "^2.1.8")),
  react: peer(npm("react", ">=18 <20")),
  reactDom: peer(npm("react-dom", ">=18 <20"), { key: "react-dom" }),
  reactNative: peer(npm("react-native", ">=0.72 <1"), { key: "react-native", optional: true }),
  vue: peer(npm("vue", ">=3.4 <4"), { optional: true }),
});

export default define(
  <Workspace name="machinalayout" runtime="nodejs">
    <Package
      name="machinalayout"
      version="0.6.1"
      license="MIT"
      kind="library"
      dependencies={{
        values: [
          deps.biome,
          deps.testingLibraryJestDom,
          deps.testingLibraryReact,
          deps.typesReact,
          deps.typesReactDom,
          deps.typesReactTestRenderer,
          deps.vueTestUtils,
          deps.jsdom,
          deps.reactTestRenderer,
          deps.tsup,
          deps.typescript,
          deps.vitest,
          deps.react,
          deps.reactDom,
          deps.reactNative,
          deps.vue,
        ],
      }}
    >
      <Policies
        // TSPack M44a cannot resolve tsup's valid relative `.js` specifiers in
        // declaration files. Keep output existence strict; the leakage walk is
        // intentionally disabled and recorded in docs/tspack-dvt-m44a.md.
        types={{ declarations: "required", missingTypes: "error", publicTypeLeakage: "ignore" }}
        boundaries={{ strict: "error" }}
      />
      <Targets
        rows={[
          {
            name: "root",
            export: ".",
            entry: "src/index.ts",
            runtime: "dist/index.js",
            types: "dist/index.d.ts",
            peers: ["react", "react-dom"],
            deps: [],
            optional: false,
          },
          {
            name: "inspect",
            export: "./inspect",
            entry: "src/inspect/index.ts",
            runtime: "dist/inspect/index.js",
            types: "dist/inspect/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "handoff",
            export: "./handoff",
            entry: "src/handoff/index.ts",
            runtime: "dist/handoff/index.js",
            types: "dist/handoff/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "deus",
            export: "./deus",
            entry: "src/deus/index.ts",
            runtime: "dist/deus/index.js",
            types: "dist/deus/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "match",
            export: "./match",
            entry: "src/match/index.ts",
            runtime: "dist/match/index.js",
            types: "dist/match/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "capture",
            export: "./capture",
            entry: "src/capture/index.ts",
            runtime: "dist/capture/index.js",
            types: "dist/capture/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "async",
            export: "./async",
            entry: "src/async/index.ts",
            runtime: "dist/async/index.js",
            types: "dist/async/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "batch",
            export: "./batch",
            entry: "src/batch/index.ts",
            runtime: "dist/batch/index.js",
            types: "dist/batch/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "iter",
            export: "./iter",
            entry: "src/iter/index.ts",
            runtime: "dist/iter/index.js",
            types: "dist/iter/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "concept",
            export: "./concept",
            entry: "src/concept/index.ts",
            runtime: "dist/concept/index.js",
            types: "dist/concept/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "diagnostics",
            export: "./diagnostics",
            entry: "src/diagnostics/index.ts",
            runtime: "dist/diagnostics/index.js",
            types: "dist/diagnostics/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "table",
            export: "./table",
            entry: "src/table/index.ts",
            runtime: "dist/table/index.js",
            types: "dist/table/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "query",
            export: "./query",
            entry: "src/query/index.ts",
            runtime: "dist/query/index.js",
            types: "dist/query/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "form",
            export: "./form",
            entry: "src/form/index.ts",
            runtime: "dist/form/index.js",
            types: "dist/form/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "command",
            export: "./command",
            entry: "src/command/index.ts",
            runtime: "dist/command/index.js",
            types: "dist/command/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "comptime",
            export: "./comptime",
            entry: "src/comptime/index.ts",
            runtime: "dist/comptime/index.js",
            types: "dist/comptime/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "react",
            export: "./react",
            entry: "src/react/index.ts",
            runtime: "dist/react/index.js",
            types: "dist/react/index.d.ts",
            peers: ["react"],
            deps: [],
            optional: false,
          },
          {
            name: "text",
            export: "./text",
            entry: "src/text/index.ts",
            runtime: "dist/text/index.js",
            types: "dist/text/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "text-react",
            export: "./text/react",
            entry: "src/text/react/index.ts",
            runtime: "dist/text/react/index.js",
            types: "dist/text/react/index.d.ts",
            peers: ["react"],
            deps: [],
            optional: false,
          },
          {
            name: "react-native",
            export: "./react-native",
            entry: "src/react-native/index.ts",
            runtime: "dist/react-native/index.js",
            types: "dist/react-native/index.d.ts",
            peers: ["react", "react-native"],
            deps: [],
            optional: true,
          },
          {
            name: "vue",
            export: "./vue",
            entry: "src/vue/index.ts",
            runtime: "dist/vue/index.js",
            types: "dist/vue/index.d.ts",
            peers: ["vue"],
            deps: [],
            optional: true,
          },
          {
            name: "text-react-native",
            export: "./text/react-native",
            entry: "src/text/react-native/index.ts",
            runtime: "dist/text/react-native/index.js",
            types: "dist/text/react-native/index.d.ts",
            peers: ["react", "react-native"],
            deps: [],
            optional: true,
          },
          {
            name: "text-vue",
            export: "./text/vue",
            entry: "src/text/vue/index.ts",
            runtime: "dist/text/vue/index.js",
            types: "dist/text/vue/index.d.ts",
            peers: ["vue"],
            deps: [],
            optional: true,
          },
          {
            name: "dispatch",
            export: "./dispatch",
            entry: "src/dispatch/index.ts",
            runtime: "dist/dispatch/index.js",
            types: "dist/dispatch/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "atlas",
            export: "./atlas",
            entry: "src/atlas/index.ts",
            runtime: "dist/atlas/index.js",
            types: "dist/atlas/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "machina",
            export: "./machina",
            entry: "src/machina/index.ts",
            runtime: "dist/machina/index.js",
            types: "dist/machina/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "style",
            export: "./style",
            entry: "src/style/index.ts",
            runtime: "dist/style/index.js",
            types: "dist/style/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
          {
            name: "static",
            export: "./static",
            entry: "src/static/index.ts",
            runtime: "dist/static/index.js",
            types: "dist/static/index.d.ts",
            peers: [],
            deps: [],
            optional: false,
          },
        ]}
      />
      <Tools
        values={[
          deps.biome,
          deps.testingLibraryJestDom,
          deps.testingLibraryReact,
          deps.typesReact,
          deps.typesReactDom,
          deps.typesReactTestRenderer,
          deps.vueTestUtils,
          deps.jsdom,
          deps.reactTestRenderer,
          deps.tsup,
          deps.typescript,
          deps.vitest,
        ]}
      />
      <Boundaries
        rows={[
          {
            transitiveFrom: "src/index.ts",
            denyDeps: ["react-native", "vue"],
            denyTypeDeps: ["react-native", "vue"],
          },
          {
            transitiveFrom: "src/react/**",
            denyDeps: ["react-dom", "react-native", "vue"],
            denyTypeDeps: ["react-dom", "react-native", "vue"],
          },
          {
            transitiveFrom: "src/react-native/**",
            denyDeps: ["react-dom", "vue"],
            denyTypeDeps: ["react-dom", "vue"],
          },
          {
            transitiveFrom: "src/vue/**",
            denyDeps: ["react", "react-dom", "react-native"],
            denyTypeDeps: ["react", "react-dom", "react-native"],
          },
          {
            transitiveFrom: "src/text/react/**",
            denyDeps: ["react-dom", "react-native", "vue"],
            denyTypeDeps: ["react-dom", "react-native", "vue"],
          },
          {
            transitiveFrom: "src/text/react-native/**",
            denyDeps: ["react-dom", "vue"],
            denyTypeDeps: ["react-dom", "vue"],
          },
          {
            transitiveFrom: "src/text/vue/**",
            denyDeps: ["react", "react-dom", "react-native"],
            denyTypeDeps: ["react", "react-dom", "react-native"],
          },
        ]}
      />
      <Publish
        include={["dist/**", "docs/**", "README.md", "LICENSE"]}
        exclude={["src/**", "test/**", "samples/**", "app/**"]}
      />
    </Package>
  </Workspace>,
);
