import { describe, expect, it } from "vitest";
import {
  M,
  anchor,
  area,
  cell,
  edge,
  fill,
  fixed,
  grid,
  gridRows,
  guide,
  hstack,
  machine,
  onLayer,
  defineLayers,
  on,
  choose,
  root,
  rows,
  skip,
  trackFill,
  trackFixed,
  screen,
  section,
  atlas,
  state,
  text,
  vstack,
} from "../../src/machina";

describe("machina exports", () => {
  it("exports M and named helpers", async () => {
    expect(
      [
        M.root,
        root,
        vstack,
        hstack,
        fixed,
        fill,
        anchor,
        rows,
        grid,
        gridRows,
        area,
        skip,
        cell,
        trackFixed,
        trackFill,
        M.edge,
        edge,
        M.guide,
        guide,
        M.text,
        text,
        M.onLayer,
        onLayer,
        M.defineLayers,
        defineLayers,
        M.screen,
        screen,
        M.section,
        section,
        M.atlas,
        atlas,
        M.machine,
        machine,
        M.state,
        state,
        M.on,
        on,
        M.choose,
        choose,
      ].every((fn) => typeof fn === "function"),
    ).toBe(true);
    const rootPackage = await import("../../src");
    expect("M" in rootPackage).toBe(false);
  });
});
