import { resolveCanvasDocumentFrames } from "./canvasFrames";
import { createCanvasUnitSystem } from "./canvasUnits";
import type { CanvasDocument } from "./sceneModel";

const rawInitialSceneDocument: CanvasDocument = {
  id: "demo-poster",
  name: "Demo Poster",
  width: 960,
  height: 640,
  unit: "px",
  unitSystem: createCanvasUnitSystem("px"),
  selectedObjectId: "headline",
  referenceGrid: {
    columns: 6,
    rows: 4,
    columnStart: "A",
    rowStart: 1,
    showBorder: true,
    showLines: false,
    showLabels: true,
  },
  layers: [
    {
      id: "background",
      name: "Background",
      visible: true,
      objectIds: ["poster-bg"],
    },
    {
      id: "product",
      name: "Product",
      visible: true,
      objectIds: [
        "product-shadow",
        "generated-product-image",
        "generated-product-alpha",
        "product-body",
        "product-highlight",
      ],
    },
    {
      id: "foreground",
      name: "Foreground",
      visible: true,
      objectIds: [
        "logo",
        "headline",
        "badge-chip",
        "cta-bg",
        "cta-label",
        "feature-chip-1",
        "feature-chip-2",
        "feature-chip-3",
      ],
    },
  ],
  objects: {
    "poster-bg": {
      id: "poster-bg",
      name: "Poster background",
      kind: "rect",
      layerId: "background",
      visible: true,
      x: 0,
      y: 0,
      width: 960,
      height: 640,
      frame: { kind: "anchor", left: 0, top: 0, right: 0, bottom: 0 },
      fill: "#f4f4f1",
      stroke: "#d7d7d2",
      tags: ["poster", "surface"],
      notes: "Document-sized product-page background panel.",
    },
    logo: {
      id: "logo",
      name: "CODEX wordmark",
      kind: "text",
      layerId: "foreground",
      visible: true,
      x: 72,
      y: 64,
      width: 180,
      height: 36,
      frame: { kind: "absolute", x: 72, y: 64, width: 180, height: 36 },
      fill: "#111111",
      text: "CODEX",
      fontSize: 30,
      fontWeight: 750,
      tags: ["brand", "wordmark"],
    },
    headline: {
      id: "headline",
      name: "Hero headline",
      kind: "text",
      layerId: "foreground",
      visible: true,
      x: 70,
      y: 134,
      width: 380,
      height: 116,
      frame: { kind: "anchor", left: 70, top: 134, width: 380, height: 116 },
      fill: "#101010",
      text: "Inspectable geometry for AI-native design.",
      fontSize: 36,
      fontWeight: 680,
      tags: ["copy", "hero"],
      notes: "Primary thesis line for the demo poster.",
    },
    "product-shadow": {
      id: "product-shadow",
      name: "Product base shadow",
      kind: "ellipse",
      layerId: "product",
      visible: true,
      x: 500,
      y: 482,
      width: 250,
      height: 44,
      fill: "#d8d8d4",
      tags: ["product", "shadow"],
    },
    "generated-product-image": {
      id: "generated-product-image",
      name: "Generated product image",
      kind: "image",
      layerId: "product",
      visible: true,
      x: 508,
      y: 176,
      width: 224,
      height: 308,
      frame: {
        kind: "referenceGrid",
        ref: "D3@0.85,0.05",
        anchor: "center",
        width: 224,
        height: 308,
      },
      src: "/assets/generated-product.svg",
      role: "image",
      alphaMapId: "generated-product-alpha",
      intrinsicWidth: 512,
      intrinsicHeight: 512,
      opacity: 1,
      blendMode: "normal",
      fit: "contain",
      tags: ["generated", "image"],
      notes: "Main generated RGB image.",
    },
    "generated-product-alpha": {
      id: "generated-product-alpha",
      name: "Generated product alpha map",
      kind: "image",
      layerId: "product",
      visible: false,
      x: 508,
      y: 176,
      width: 224,
      height: 308,
      src: "/assets/generated-product-alpha.svg",
      role: "alphaMap",
      intrinsicWidth: 512,
      intrinsicHeight: 512,
      fit: "contain",
      tags: ["generated", "alpha-map"],
      notes: "White means opaque, black means transparent.",
    },
    "product-body": {
      id: "product-body",
      name: "Product silhouette body",
      kind: "rect",
      layerId: "product",
      visible: true,
      x: 520,
      y: 200,
      width: 190,
      height: 284,
      frame: {
        kind: "referenceGrid",
        ref: "D3@0.84375,0.1375",
        anchor: "center",
        width: 190,
        height: 284,
      },
      fill: "#151515",
      stroke: "#000000",
      radius: 34,
      tags: ["product", "silhouette"],
    },
    "product-highlight": {
      id: "product-highlight",
      name: "Product highlight",
      kind: "ellipse",
      layerId: "product",
      visible: true,
      x: 565,
      y: 238,
      width: 62,
      height: 170,
      fill: "#ffffff",
      tags: ["product", "lighting"],
      notes: "White ellipse that makes the silhouette read as glossy.",
    },
    "cta-bg": {
      id: "cta-bg",
      name: "CTA button background",
      kind: "rect",
      layerId: "foreground",
      visible: true,
      x: 72,
      y: 390,
      width: 188,
      height: 48,
      frame: { kind: "anchor", left: 72, top: 390, width: 188, height: 48 },
      fill: "#111111",
      radius: 2,
      tags: ["button", "cta"],
    },
    "cta-label": {
      id: "cta-label",
      name: "CTA button label",
      kind: "text",
      layerId: "foreground",
      visible: true,
      x: 96,
      y: 405,
      width: 142,
      height: 20,
      fill: "#ffffff",
      text: "Inspect scene",
      fontSize: 15,
      fontWeight: 700,
      tags: ["button", "copy"],
    },
    "badge-chip": {
      id: "badge-chip",
      name: "Price chip",
      kind: "rect",
      layerId: "foreground",
      visible: true,
      x: 707,
      y: 154,
      width: 112,
      height: 38,
      fill: "#ffffff",
      stroke: "#111111",
      radius: 19,
      tags: ["badge", "commerce"],
      notes: "A product-page badge preserved as editable geometry.",
    },
    "feature-chip-1": {
      id: "feature-chip-1",
      name: "Feature chip: IDs",
      kind: "rect",
      layerId: "foreground",
      visible: true,
      x: 72,
      y: 500,
      width: 138,
      height: 34,
      frame: {
        kind: "referenceGrid",
        ref: "A4@0.88125,0.23125",
        anchor: "center",
        width: 138,
        height: 34,
      },
      fill: "#ffffff",
      stroke: "#cfcfca",
      radius: 17,
      tags: ["feature", "chip"],
    },
    "feature-chip-2": {
      id: "feature-chip-2",
      name: "Feature chip: Bounds",
      kind: "rect",
      layerId: "foreground",
      visible: true,
      x: 224,
      y: 500,
      width: 158,
      height: 34,
      fill: "#ffffff",
      stroke: "#cfcfca",
      radius: 17,
      tags: ["feature", "chip"],
    },
    "feature-chip-3": {
      id: "feature-chip-3",
      name: "Feature chip: Commands",
      kind: "rect",
      layerId: "foreground",
      visible: true,
      x: 398,
      y: 500,
      width: 182,
      height: 34,
      fill: "#ffffff",
      stroke: "#cfcfca",
      radius: 17,
      tags: ["feature", "chip"],
    },
  },
};

export function createInitialCanvasDocument(): CanvasDocument {
  return resolveCanvasDocumentFrames(rawInitialSceneDocument);
}

export const initialSceneDocument: CanvasDocument = createInitialCanvasDocument();
